name: dev
on: workflow_dispatch
jobs:
  frstjob:
    runs-on: windows-latest
    steps:
      - name: greet
      - run: echo "happy new"
  secndjob:
    runs-on: ubuntu-latest
    steps:
      - name: new
        run: echo "how ru"
      - name: naya
        run: echo "im finre"
    
