name: osinfo
on: workflow_dispatch

jobs:
  frstjob:
    runs-on: ubuntu-latest
    steps:
      
      - name: github runer
        run: echo "welcmome"
  secodjob:
    runs-on: self-hosted
    steps:
      - name: os specs
        run: cat /etc/os-release
