name: osinfo
on: workflow_dispatch

jobs:
  frstjob:
    runs-on: ubuntu-latest
    steps:
      - name: os info
        run: cat /etc/os-release
      - name: mulipltcmds
        run: |
          lscpu
          free -mh
        
        
