name: runner
on: workflow_dispatch

jobs:
  frstjob:
    runs-on: ubuntu-latest
    steps:
      - name: create folder
        run: | 
          cd 
          mkdir git
          ls
      
      
      - name: os speccs
        run: cat /etc/os-release
  secodjob:
    runs-on: self-hosted
    steps:
      - name: create folder
        run: |
          cd
          mkdir self
          ls
