name: slack
on: workflow_dispatch
jobs:
  secndjob:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo " frst job"
  frstjob:
    runs-on: ubuntu-latest
    steps:
      - name: salck notification
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{secrets.SLACK_PASSWD}}
          webhook-type: incoming-webhook
          payload: |
            channel: githb-actions
            text: "trieger new noticiafytion"
