name: slack-notification
on: workflow_dispatch
jobs:
  slackjob:
    runs-on: ubuntu-latest
    steps: 
      - name: slac noticiafytion
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{secrets.NEWWEBHOOK}}
          webhook-type: incoming-webhook
          payload: |
            channel: devops
            text: " devloper shiv made some chnages "
