name: evn variable
on: workflow_dispatch
env:
  
  DASHING: "sehwag"

jobs:
  frstjob:
    runs-on: ubuntu-latest
    steps:
      - name: greeet
        run: echo "hi team, ${{vars.GREET}}"
      - name: login azure
        run: echo "login using this ${{secrets.AWS_PASSWD}}"
